### ISSUE TITLE
Current highlighted line on Terminal not visible

### ISSUE THREAD

**Issue by benfrain** [arcticicestudio/nord-iterm2#9] opened 2019-09-25 11:45 UTC
First of all, I love this theme; so hope this can be sorted!

You can see here that the current line doesn't show when using Nord. 
<img width="606" alt="Screenshot 2019-09-25 at 12 41 39" src="https://user-images.githubusercontent.com/1318466/65597851-f8447a00-df91-11e9-8163-0c805b80bed2.png">

If I switch to a default theme such as Solarized it displays fine:

<img width="608" alt="Screenshot 2019-09-25 at 12 44 10" src="https://user-images.githubusercontent.com/1318466/65597993-56715d00-df92-11e9-8487-0b1868dd2be7.png">

In addition, I noticed the issue in Neovim at first when cycling through search selections. In that case, when pressing <kbd>n</kbd> to move to the next match, the selected match would disappear too:

<img width="593" alt="Screenshot 2019-09-25 at 12 37 08" src="https://user-images.githubusercontent.com/1318466/65598126-9fc1ac80-df92-11e9-9fc9-6ac9e476cd51.png">

Is this is known issue? Is there any setting I can change in iTerm to fix (running 3.3.4)?

**Comment by arcticicestudio** [comment] 2019-09-27 06:49
Hi @benfrain :wave:, thanks for your contribution :+1:
Are you running _nvim_ within a multiplexer like _tmux_? These setups require some additional configurations in order to make colors work correctly.
I'll try to reproduce the problem with the current line, but I've also never saw that the current line has a special highlighting. I'll need to check if this is maybe a feature added in later versions.

**Comment by benfrain** [comment] 2019-09-27 07:01
Hi! 👋 

No tmux. Just Neovim direct from iterm.

**Comment by benfrain** [comment] 2019-10-04 20:20
After further investigation, I'm not sure this is to do with Nord iterm2 solely.
I noticed that I don't have this issue using iterm2 on my work computer. So I copied the iterm config json and applied it to my problematic setup and it now works as expected. There is something in the iterm setup that causes this issue.

Here are the working and non-working iterm json configs:

Working: https://gist.github.com/benfrain/11c7b4c6e7cde22348f6f5e6aca64861

Non-working: https://gist.github.com/benfrain/c18fd9bba2dbd56cdbb4c5ef5d25e614

Hopefully that may help reveal the cause of this issue.

**Comment by arcticicestudio** [comment] 2019-10-05 06:48
First of all, good that the problem is solved :smile: 
Thanks for the feedback and the _Gists_, I've compared both configurations and found 2 possible options that might cause the problem where all of them are included in the non-working set:

### Cursor Guide

:link: [Line 478][l478]
```diff
     "Use Bright Bold": true,
+    "Use Cursor Guide": true,
     "Use Italic Font": true,
```
I guess this option has the highest probability to be the root cause: The [**Cursor Guide** option][cg]
> The cursor guide is a horizontal rule that indicates the vertical position of the cursor. You can adjust its color, including alpha value, to make it more visible against your background color.

This is exactly what's visible on your screenshots and I guess it causes problems due to its rendering style using a color value with a alpha layer for opacity.
Also see the documentation section about [**Cursor Finery**][cf] that can be enabled when using the _block_ cursor style.

### Underline Color

:link: [Line 482][l482]
```diff
+    "Use Underline Color": false,
     "Vertical Spacing": 1,
```
It is possible that the [**Underline Color**][ulc] option also causes problems in combination with the _Cursor Guide_ option when rendering underlined elements.
> If enabled, this color will be used for all underlining, independent of the color that underlined characters have themselves.  

:arrow_right: You could try to play around with both options to see if this causes the problem again, but I'll also try to reproduce it to maybe include it in the docs/FAQ of this theme.
I close this isseu for now since the problem is resolved, but feel free to post your findings :wink: 

[cf]: https://www.iterm2.com/documentation-highlights.html#cursor-finery
[cg]: https://www.iterm2.com/documentation-preferences-profiles-colors.html#cursor-guide
[l478]: https://gist.github.com/benfrain/c18fd9bba2dbd56cdbb4c5ef5d25e614#file-item-config-home-json-L478
[l482]: https://gist.github.com/benfrain/c18fd9bba2dbd56cdbb4c5ef5d25e614#file-item-config-home-json-L482
[ulc]: https://www.iterm2.com/documentation-preferences-profiles-colors.html#underline-color

**Closed as completed by arcticicestudio** 2019-10-05 06:48 UTC
Labels: resolution-user-side, context-ui, scope-compatibility, scope-ux, type-support
